### ISSUE TITLE
Optional listing generation

### ISSUE THREAD

**Issue by nihirash** [envenomator/agon-ez80asm#11]
Is it possible make it disabled by default or disable by CLI parameter?

After updating to 1.03 RC4 with FF_TINY I've got really long compilation time of my gopher browser.

I'll prefer have this option that will be on demand(I'd prefer have more compilation speed over listings that I don't use in 90% of compilations).

**Comment by envenomator** [comment]
in v096 it's disabled by default now, enabled with the -l option
