### ISSUE TITLE
License for Source Code?

### ISSUE THREAD

**Issue by rprouse** [envenomator/agon-ez80asm#13]
First, thanks for creating this. It is great to be able to work in assembly directly on the Agon and it is also a great example of how to code for the Agon in C. To that end, may I ask what license you are releasing the code under? I'd like to use at least the MOS specific code in my personal projects.

**Comment by envenomator** [comment]
Hi Rob,
You're welcome and great question; I hadn't really thought about this. I've just applied the MIT license to the repo.

**Comment by rprouse** [comment]
Thank you for your work and the quick answer.

<img src="https://media1.giphy.com/media/RipfZWzjUDH25euMpM/giphy.gif"/>
