### ISSUE TITLE
No Windows, MacOS or Linux version

### ISSUE THREAD

**Issue by snakebyte69** [envenomator/agon-ez80asm#15]
Would be nice to have this as a cross-compiler also, spasm-ng is not 100% compatible.

My attempt to build it on MacOS
-----

% make
gcc -g -Wall -c src/assemble.c -o obj/assemble.o
In file included from src/assemble.c:7:
In file included from src/assemble.h:4:
src/./stdint.h:23:14: error: typedef redefinition with different types ('char' vs 'signed char')
typedef char int8_t;
             ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types/_int8_t.h:30:31: note: previous definition is here
typedef signed char           int8_t;
                              ^
In file included from src/assemble.c:7:
In file included from src/assemble.h:4:
src/./stdint.h:29:14: error: typedef redefinition with different types ('long' vs 'int')
typedef long int32_t;
             ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types/_int32_t.h:30:33: note: previous definition is here
typedef int                     int32_t;
                                ^
In file included from src/assemble.c:7:
In file included from src/assemble.h:4:
src/./stdint.h:30:23: error: typedef redefinition with different types ('unsigned long' vs 'unsigned int')
typedef unsigned long uint32_t;
                      ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_types/_uint32_t.h:31:22: note: previous definition is here
typedef unsigned int uint32_t;
                     ^
In file included from src/assemble.c:8:
In file included from src/globals.h:8:
In file included from src/macro.h:8:
src/utils.h:23:5: error: conflicting types for 'strcasecmp'
int strcasecmp(char *s1, char *s2);
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/strings.h:78:6: note: previous declaration is here
int      strcasecmp(const char *, const char *);
         ^
In file included from src/assemble.c:15:
src/mos-interface.h:22:10: fatal error: 'defines.h' file not found
#include <defines.h>
         ^~~~~~~~~~~
5 errors generated.
make: *** [obj/assemble.o] Error 1

**Comment by envenomator** [comment]
Please comment out the '#define AGON' line in config.h and try again. I'm developing this under Windows/WSL with Ubuntu. When finally compiling for the Agon platform with the ZDS compiler, I set just this line again.

**Comment by snakebyte69** [comment]
I had to add /obj as a directory
it compiles now. Thanks.

It's working under Sublime Text on MacOS
I have a binary I can upload if you like.

**Comment by snakebyte69** [comment]
I have compiled versions  for MacOS, Windows and Linux.
Give me access and I will upload them.

**Comment by envenomator** [comment]
I have adopted a number of changes in the build scripts to facilitate building on other platforms. I'll not be providing direct support for these, nor hosting binaries for other platforms as people would expect me to update these as well every time I update the main code. Hope this helps.
