### ISSUE TITLE
Using RST.LIS not working in ADL mode

### ISSUE THREAD

**Issue by dsnopek** [envenomator/agon-ez80asm#18]
When using `.ASSUME ADL=1`, and a `rst.lis` instruction, I get the `Suffix not matching mnemonic / ADL mode` error.

I'm not 100% sure (because I'm pretty new to ez80 assembly), but I think that `rst.lis` is valid when in ADL mode?

Or, if it's not valid, it's at least accepted (and translated to something valid) when used with spasm-ng or ZDS II :-)

This came up for me specifically because it's used in mos_api.inc:

https://github.com/breakintoprogram/agon-mos/blob/main/src/mos_api.inc#L224

... and the MOS API examples in the official Agon documentation:

https://github.com/breakintoprogram/agon-docs/wiki/MOS-API

**Comment by envenomator** [comment]
I have created a support case at Zilog to clarify this; their ez80 CPU datasheet doesn't state RST.LIS as a valid instruction in ADL==1 mode, but it does in ADL==0 mode. However, their ZDSII assembler accepts RST.LIS in both modes..

**Comment by envenomator** [comment]
Fixed in v0.98
