### ISSUE TITLE
Enabled listing can broke macros work(including files)

### ISSUE THREAD

**Issue by nihirash** [envenomator/agon-ez80asm#24]
I have macro:
```
   macro DEFSPRITE num, file
   db 23, 27, 0
   db num
  db 23, 27, 1
  dw 16, 16
  incbin file
   endmacro
```

And if I run compilation with `-l` flag it shows error that file can't be included. 

Without flag -l everything works fine.

**Comment by envenomator** [comment]
I'm suspecting this to be a case where we run up against the hard MOS file-open limit, where a maximum of 8 files can be open at a time. That is a ccompiled-in hard limit of MOS currently... 
ez80asm needs:
- 5 handles as a starting point (In / out / local labels / anonymous labels / filedelete list for clean-up)
- 1 extra if listing is requested
Which leaves 2 handles to allow for macros / includes / incbins, which can be nested. That is tight, until one perhaps makes heavy use of include files with macros in them, using a incbin statements and also requests a listing. Is that how you are using it currently?

If that's the case, we'd need to ask Dean if he can upgrade the MOS file-open limit at the next release

**Comment by nihirash** [comment]
Ok! :-) 

Looks like it's not issue of ez80-asm

**Comment by envenomator** [comment]
I've rewritten the io cleanup handler in such a way, it dynamically reconstitutes the deletelist and doesn't use a delete file. That saves one open filehandle, so with the latests commit rokky now assembles with a listing, as it stays just under the open filehandle maximum of MOS. Will put this code out in v0.98
