### ISSUE TITLE
Cross Compiler Version does not compile - Hello World 16

### ISSUE THREAD

**Issue by snakebyte69** [envenomator/agon-ez80asm#26]
<img width="980" alt="Screenshot 2023-05-06 at 7 28 42 am" src="https://user-images.githubusercontent.com/39090848/236571926-0d484678-ed82-467f-99a7-439930d08991.png">

**Comment by envenomator** [comment]
What is on line 47?

**Comment by envenomator** [comment]
Ah; you are just trying to assemble code from Dean’s example hello world I see. That code was written for the ZDS ASSEMBLER
