### ISSUE TITLE
Macro arguments don't work with data directives

### ISSUE THREAD

**Issue by SlithyMatt** [envenomator/agon-ez80asm#28]
Macro arguments are not being expanded correctly when used in the context of a data directive.
Example:

`macro initdata foo,bar`
`db foo`
`dw far`
`endmacro`

You should be able to pass in numerical expressions and get the data allocated, as long as the value passed to the argument fits within the width of the data directive. Currently, the names of the arguments are not getting replaced in the macro instantiations in these directives, as they would for code instructions.

Good example:
`initdata 42,$1337`

Should result in the hex data:
`2A 37 13`

Bad example:
`initdata 2001,2010`

Should result in an assembly error, as 2001 will not fit in a single byte.

**Comment by envenomator** [comment]
![image](https://github.com/envenomator/agon-ez80asm/assets/47718809/a31fcccc-d5bb-43d2-999d-91655d81fddb)

Works from v0.97 for me, when applying your example code without the typo: 'far' should be 'bar'.

**Comment by nihirash** [comment]
Here code where I've used it: https://github.com/nihirash/Agon-rokky/blob/efdc5d454dffc2bac1d4f5b65375eb6001bb2a52/src/vdp.inc#L3

And it works fine!
