### ISSUE TITLE
Linux Port

### ISSUE THREAD

**Issue by IGBC** [envenomator/agon-ez80asm#3]
Hi I am working on bringup of my own custom board with an eZ80 CPU on it. 

Your assembler seems to actually be one of the best made available for this chip, which is sad. The support for these chips is awful. 

I am not familiar with the agon project or what it's api's look like, but how possible would it be to port this to run on "normal" desktop linux/unix. I need a robust assembler to bring my board up. SPASM-NG is awful. FASMG doesn't work and the native zilog tools are windows only.

many thanks

- Segfault

**Comment by envenomator** [comment]
Hi Segfault,

Good to hear you're working on your own custom board!
The agon project is an ez80-based board, with 512K RAM added, PS/2 keyboard interface and an ESP32 pico acting as a VGA terminal, using high-speed serial between ez80 and ESP32 to send display commands. Details and schematics can be found at https://www.thebyteattic.com/p/agon.html

Development for my assembler started on a Linux desktop and after the Agon APIs matured a bit, I ported it over to Agon. As development on the assembler is easier on a Linux desktop with it's rich ecosystem of tools, it still compiles to Linux. You just need to remove the '#define AGON' in config.h, do a make clean / make, and you should have a working Linux binary in bin/
The Agon RAM starts at address 0x40000; you should probably set the #define START_ADDRESS differently for your platform in config.h

As the Agon still only has very rudimentary file support (only fputc/fgetc/feof/fopen), the fread/fwrite methods are stubbed which will be removed later on in the Agon development cycle. And to reverse-port it back to Linux, I had to abstract the Agon filehandlers to FILE *. I'm using the same slower calls on Linux, but this works fine. The code changes compiler behavior based on the #define AGON flag.

Please be aware that this code is in beta. It assembles several sourcefiles just fine, but there will be some bugs and limitations. I'm pretty sure that the opcodes assemble correctly, that's been tested intensively. The ADL suffixes have faced less scrutiny and might have some issues.

Enjoy!
