### ISSUE TITLE
Compiling for Windows - Not working

### ISSUE THREAD

**Issue by snakebyte69** [envenomator/agon-ez80asm#38]
>make
clang.exe /Zi /W4 /nologo /DWINDOWS /D_CRT_SECURE_NO_WARNINGS /c /Foobj/assemble.o src/assemble.c
clang: error: no such file or directory: '/Zi'
clang: error: no such file or directory: '/W4'
clang: error: no such file or directory: '/nologo'
clang: error: no such file or directory: '/DWINDOWS'
clang: error: no such file or directory: '/D_CRT_SECURE_NO_WARNINGS'
clang: error: no such file or directory: '/c'
clang: error: no such file or directory: '/Foobj/assemble.o'
make: *** [Makefile:43: obj/assemble.o] Error 1

**Comment by snakebyte69** [comment]
windows.mk does not work with gcc or clang

**Comment by snakebyte69** [comment]
it works if you use the makefile from 0.96
gcc is easier to install for Windows than clang

**Comment by envenomator** [comment]
I did mention earlier that I won't directly support cross-compilation builds. Rob Prouse was kind enough to provide some guidance and asked me to change some build scripts to let you build on Windows with VC++ 2022.
