### ISSUE TITLE
64KB/128KB(with macros) binary output limit when assembling on the Agon itself

### ISSUE THREAD

**Issue by envenomator** [envenomator/agon-ez80asm#39]
As reported by SlithyMatt on discord. Details to follow.

**Comment by SlithyMatt** [comment]
This file won't build on Linux: https://gist.github.com/SlithyMatt/10d052ac871f394a0eb705369c88a927

**Comment by SlithyMatt** [comment]
This file will build on Linux, but not on the Agon: https://gist.github.com/SlithyMatt/3e4fc0137c3d335c07446839e5e82e64

**Comment by envenomator** [comment]
> This file won't build on Linux: https://gist.github.com/SlithyMatt/10d052ac871f394a0eb705369c88a927

I will using my latest commit. There was a issue in the posix interoperability layer after a certain amount of calls to open a new file. This wasn't seen before, but triggered with this code that repeatedly invokes a macro a significant number of times. Perfectly legal, but triggering the issue.

> This file will build on Linux, but not on the Agon: https://gist.github.com/SlithyMatt/3e4fc0137c3d335c07446839e5e82e64

I don't have access to an actual Agon in the next few days, but the emulator assembles it fine with the 0.99 version. But given the amount of .dbs in the macro and the large number of invocations to the macro, its just an enormous lot of work for the Agon to do. The emulator finishes assembling it, but this takes several minutes on a modern PC.

**Comment by envenomator** [comment]
Macro expansion also wasn't using buffered I/O. But using macros with significant amounts of lines may well benefit from using it. Will commit this change later
