### ISSUE TITLE
incbin directive

### ISSUE THREAD

**Issue by nihirash** [envenomator/agon-ez80asm#4]
Hello!

Thank you for your great assembler for eZ80.
If it's possible, please add support of including binaries directly from sources.

**Comment by envenomator** [comment]
Hi Alexander!
That's a great idea; I'll put it on my to-do list for the next release.

**Comment by nihirash** [comment]
Currently I did something like this: https://github.com/nihirash/Agon-MOS-Tools/tree/main/bin2asm

I did it using your assembler but I think native solution will work a bit better.

**Comment by envenomator** [comment]
It's included now in the latest code, commit [8c6f78c]
