### ISSUE TITLE
Implementing .STRUCT / .ENDSTRUCT

### ISSUE THREAD

**Issue by radekh** [envenomator/agon-ez80asm#45]
Hello Jeroen,
I try to use mos_api.inc from agon-mos however it failed to process.  Some errors are minor issues, however I realized ez80asm do not understand structures.

Are you planning to add this construct?

**Comment by envenomator** [comment]
Hi Radek,

The mos_api.inc is has been written by Dean for use in the ZDS assembler, which has a somewhat different syntax.
I'm not currently planning to include structures in ez80asm
