### ISSUE TITLE
Labels can't start with PO or PE

### ISSUE THREAD

**Issue by sijnstra** [envenomator/agon-ez80asm#47]
The parser confuses flags and labels. e.g LD HL,(POS1) will fail even if POS1 is defined. Similarly, 	JR	Z, pe_none also fails because the label starts with PE.

**Comment by envenomator** [comment]
The behavior you are describing has been fixed a while back in release https://github.com/envenomator/agon-ez80asm/releases/tag/v0.106. Please let me know if running the latest release helps, or if something is still wrong.

**Comment by sijnstra** [comment]
My apologies! Looks like I had an old version that was bundled with something else. Thanks for responding quickly!

**Comment by envenomator** [comment]
No worries, glad that it's working now!
