### ISSUE TITLE
Issue with large labels

### ISSUE THREAD

**Issue by leuat** [envenomator/agon-ez80asm#48]
Hi there! I'm currently adding support for the agon in TRSE, and I'm using ez80asm. TRSE generates labels that are pretty large, and ez80asm fails / produces incorrect machine code whenever a label is larger than about 33 characters.

**Comment by envenomator** [comment]
Hi!
That is a compiled-in maximum to save on memory space, configured in config.h (#define MAXNAMELENGTH                32 // Maximum name length of labels/macros/mnemonics)

**Comment by leuat** [comment]
thanks!

**Comment by leuat** [comment]
but since people will be using TRSE to develop for the agon, they'll expect to just download ez80asm for windows etc.. if the default value is 32, then assembling will fail for everyone else but me

**Comment by envenomator** [comment]
Yeah, I understand. But frankly, 32 character labels are already really long, having a potential impact on the assembler when lifted to allow even more. If later on someone needs labels with even larger lengths, what to do then?
The premise of ez80asm was to provide an onboard assembler for the Agon itself for people to experiment with; it's important for me to keep that focus.

**Comment by leuat** [comment]
Closing this one, since I managed to extend my internal Z80 assembler in TRSE to 24 bit addreses / ez80! anyway thanks
