### ISSUE TITLE
DL directive broken?

### ISSUE THREAD

**Issue by nihirash** [envenomator/agon-ez80asm#7]
i've tried configure UART1 via OS and there was required save speed as LONG value:
```
  ld IX, uart_config
; ...
uart_config:
    dl 115200
    db 8
; other fields are byte lenght and worked fine
```

I've got "Invalid mnemonic" error.

**Comment by envenomator** [comment]
The documentation was a little ahead this time. The DL command was in, but with a 'DW24' mnemonic.
Fixed in the last commit, also in /binaries
