### ISSUE TITLE
instructions

### ISSUE THREAD

**Issue by richardturnnidge** [envenomator/agon-ez80asm#77]
NOTE: the new binary for 1.5 now needs to be placed inside the BIN directory, not the MOS directory.

I had to do this for it to work for me, but not clear in the instructions, especially for existing fools (like me) who just copied over top of the existing version...

**Comment by envenomator** [comment]
It's literally in the README, first paragraph ;-)

**Comment by richardturnnidge** [comment]
How on earth did I miss that....

I know, I went straight to releases to grab latest version and didn't scroll down on the main page. Doh...
