### ISSUE TITLE
.DS directive should only define empty space

### ISSUE THREAD

**Issue by envenomator** [envenomator/agon-ez80asm#79]
Currently, the .DS directive is being implemented as .BLKB.
This results in programs ending in .DS statements with unnecessary bytes that shouldn't be added to the program.

**Comment by nihirash** [comment]
I think better make explicit finish of binary export

**Comment by envenomator** [comment]
fixed in https://github.com/envenomator/agon-ez80asm/commit/4e02e493d30b1f3fc5138e26d363e445c38a6db2

**Comment by envenomator** [comment]
Released in v1.6
