### ISSUE TITLE
Can't find asm.bin

### ISSUE THREAD

**Issue by SanPollo** [envenomator/agon-ez80asm#8]
The README.md says to place both the asm.bin and asm.ldr into the /mos directory on the microSD card.

I can find asm.ldr in the /binaries directory in the repository, but I can't find asm.bin anywhere.

Please would you upload a copy of asm.bin into the /binaries directory?

**Comment by envenomator** [comment]
The asm.ldr in /binaries is actually the latest untable version of the assembler payload, with a few bugfixes that aren't released yet. The latest release can be found here - https://github.com/envenomator/agon-ez80asm/releases, containing both files. The asm.bin hasn't changed, that is just the loader program for the assembler payload.

**Comment by envenomator** [comment]
I've put out a v0.94 release. You can find all files at https://github.com/envenomator/agon-ez80asm/releases/tag/v0.94
