### ISSUE TITLE
ORG $-1 directive recognised in listing but not in the generated binary file. 

### ISSUE THREAD

**Issue by SimonStickling** [envenomator/agon-ez80asm#80]
Version 1.4 of the Agon Light ez80asm assembler.
Code such as:
	DW	LABEL-$
	ORG	$-1
	DW	LABEL-$
	ORG	$-1	
	DS	48
LABEL:
Will show in the ez80asm listing that the ORG statement decrements the assembly address.
However, the bin file does not show this. The .lst and .bin files disagree.
The generated code is different from the listing.

Background: a common coding technique is the generate an array of offsets to relevant code.
This is often an array of single bytes with low offsets.  
 DB LABEL-$ will not be accepted by the Agon Light ez80asm.
The Zilog ZDS tool has an embedded ez80asm assembler that offers LOW( ) and HIGH ( ) functions to assist e.g. LOW(LABEL-$).

The documntation says ORG should be followed by a constant.
Does this mean that ORG $-1 is itself invalid?
How should the coding required be generated?

**Comment by envenomator** [comment]
I'm currently at release 1.6, which does support DB label-$
![image](https://github.com/envenomator/agon-ez80asm/assets/47718809/b4b9698c-f075-4ff7-bffa-e48f35278167)

1.6 also correctly handles empty space at the end of a program using the DS statement

**Comment by envenomator** [comment]
I've checked ZDS, which gives 'ERROR (507) Relocatable values not allowed in this expression' when given a
ORG $-1

While both ez80asm and ZDS allow for setting a different ORG later on in code, it doesn't reflect on either's assembled output.

**Comment by SimonStickling** [comment]
I accept your explanation but with some minor points: the error does not get shown in the assembler output messages or the listing. It doesn't fail the assembly or warn that the code generated will be different from the listing.Does it need a setting to show warnings?I am now completely stuck on how to generate a value that is acceptable to a DB instruction from an expression using a relocatable value (a location). Can you help?I can understand that the assembler may not know whether the expression would be corrupted on only moving bits 7-0 to the DB. But isn't this over-protective? Isn't this similar to type-casting in the C language e.g.... = (byte) valueor... LOW(value)In fact the assembler can know on pass 2 whether the expression will actually fit in a byte or on pass 1 if the location is before the DB.It could warn then...Thank you for you help and assembler.On 23 Apr 2024 13:57, Jeroen Venema ***@***.***> wrote:
I've checked ZDS, which gives 'ERROR (507) Relocatable values not allowed in this expression' when given a
ORG $-1
While both ez80asm and ZDS allow for setting a different ORG later on in code, it doesn't reflect on either's assembled output.

**Comment by SimonStickling** [comment]
Hi, good news. I wish I had seen this before my recent commentsWorry now is I'm on Quest 1.4 and uncertain whether installing Console8 2.2.0+ MOS on an Agon Light 2 is risky...(For your amusement the code involved is the ZX Spectrum 48k z80 ...).On 23 Apr 2024 13:18, Jeroen Venema ***@***.***> wrote:
I'm currently at release 1.6, which does support DB label-$
image.png (view on web)

**Comment by envenomator** [comment]
Good to hear; starting 1.6, the DB/DW statements are much less strict and only give warnings if fed a larger number than the length can hold.

You can also use compound statements to get to the high/low byte of a constant or label, like so
 .db $>>16 ; gives the high byte
 .db $ & 0xFF; gives the low byte
 
As a side-note, the AgonLight2 is less risky then you might think. When the agon-flash utility fails somehow and the MOS gets borked, you can always use the agon-recovery utility, which requires just two dupont jumpercables to recover MOS. I've written both utilities and done literally hundreds of flash installs/recoveries.

**Comment by SimonStickling** [comment]
Some news:I tried the fab-agon-emulator 9.0.43 with ez80asm 1.6.Happily DB label-$ now passes. Didn't try if the calculation is >255.However ORG $-1 behaviour is unchanged (but I don't need it now!).When trying to assemble 20,000 source lines and generate around 16k of binary I get "out of memory" and an ungraceful end. Worked on 1.2! Trivia: assembler now objects to 1234 // 5.I was looking for a modulus operator like 1234 % 256. Would be useful.Thanks.Simon.On 23 Apr 2024 17:22, Jeroen Venema ***@***.***> wrote:
Good to hear; starting 1.6, the DB/DW statements are much less strict and only give warnings if fed a larger number than the length can hold.
You can also use compound statements to get to the high/low byte of a constant or label, like so
.db $>>16 ; gives the high byte
.db $ & 0xFF; gives the low byte
As a side-note, the AgonLight2 is less risky then you might think. When the agon-flash utility fails somehow and the MOS gets borked, you can always use the agon-recovery utility, which requires just two dupont jumpercables to recover MOS. I've written both utilities and done literally hundreds of flash installs/recoveries.

**Comment by envenomator** [comment]
org behavior is similar to other assemblers on the market, which I agree with behavior-wise, so that will not be changed.
Original question has been resolved a while back. User was running an older version of the assembler.
