### ISSUE TITLE
Macro error messages are unhelpful

### ISSUE THREAD

**Issue by jblang** [envenomator/agon-ez80asm#82]
If I call a macro with the incorrect parameters, I get an error message like this:

My macro is defined like this:

```
    macro VduProgAdjust buffer, offset, operation, operand
    defb VDU_Command, VDU_SystemCommand, VDU_BufferCommand
    defw buffer
    defb VDU_BufferAdjust
    defb operation
    defw offset
    defb operand
    endmacro
```

A proper invocation would be like this:

```
    VduProgAdjust TileMapID, TileMapChar, VDU_BufferOpSet, 0
```

"Proper" assumes that all the labels are defined. If I change one of the parameters to an undefined label, like this:

```
    VduProgAdjust undefined, TileMapChar, VDU_BufferOpSet, 0
```

Then all it tells me is this:

```
Macro [VduProgAdjust] in "vdu/buffer.inc" line 115 - Unknown label, invalid number
    defw buffer
```

This isn't helpful for finding the source of the error because it doesn't tell me which invocation of the macro caused the error. The macro itself is fine.  So I have to go through and one by one inspect all the calls to the macro until I find the offending line.

Can't it report the line that the macro was called on?

**Comment by envenomator** [comment]
It already does, if you expand the macro using the comma between parameters, as per the documentation example. If you're using a space or something different, then the entire argument is treated as a single parameter, resulting in the error you see.

**Comment by jblang** [comment]
Sorry, I should have included more context. I've updated the description with more.  FWIW, I'm using commas.  This is occurring on v1.6, the windows cross assembler but it's not specific to this. I know I've seen it on the native assembler before too.

**Comment by envenomator** [comment]
Ah ok, so 1.6 currently reports any errors encountered during expansion, by stating in which line _within _ the macro the error is at. This error case is indeed different than I thought you were asking to report on; when one gives the macro an incorrect argument, you'd like to see the line reported where it is expanded from, not to, to track down the incorrect invocation. That's clear. I'll need to check how this could be accomplished.

**Comment by jblang** [comment]
Yes, that's what I'd like.  Actually it may be best to report both, since there actually could be an error in a macro, but then also report where the macro was called from in case it was due to a bad parameter value.

**Comment by envenomator** [comment]
I've added this as a new feature in https://github.com/envenomator/agon-ez80asm/commit/7390a158e178435853c6a5d9f69589e765247734

**Comment by jblang** [comment]
Great! Thank you very much. Do you have instructions for building on windows or can you share an exe for me to test?

**Comment by envenomator** [comment]
Hi, give me a few days to provide a new release. I'm also adding in one additional feature to report on the context of some errors, to clarify erroneous parameters/operands to the user.

**Comment by envenomator** [comment]
Try this alpha version of 1.7 for windows: https://we.tl/t-13e7NbPMto

**Comment by envenomator** [comment]
Warnings during a macro expansion are now displayed alongside their invocation location - https://github.com/envenomator/agon-ez80asm/commit/6b1f0b02d34e8b5b019f9ba2c47d2ba3244c9089

**Comment by envenomator** [comment]
I'm releasing these enhancements as part of v1.7
