### ISSUE TITLE
SIGTRAP when I'm trying build ZINC with 1.7 version 

### ISSUE THREAD

**Issue by nihirash** [envenomator/agon-ez80asm#83]
```shell 
 make
date '+%Y.%m.%d' >.version
(cd src/zinc/edos && ez80asm -i -l edos.asm)
Assembling edos.asm
Listing to edos.lst
Pass 1...
Pass 2...
Done in 0.00 seconds
(cd src/zinc && ez80asm -i -l zinc.asm ../../zinc.bin)
Assembling zinc.asm
Listing to zinc.lst
Pass 1...
/bin/sh: line 1:  1143 Trace/BPT trap: 5       ez80asm -i -l zinc.asm ../../zinc.bin
```

I'm trying build my current dev branch located [here](https://github.com/nihirash/ZINC/tree/dev).

**Comment by envenomator** [comment]
Looks like a problem with the -O2 optimization flag used for release binaries.

**Comment by envenomator** [comment]
Please redownload the Linux binary from the releases tab

**Comment by nihirash** [comment]
Sorry, I've forget say that it happens on macOS.

I've found that issue happen on commit: https://github.com/envenomator/agon-ez80asm/commit/9ab19398fce774ea73ad2160bb52c0eddf8ca966

Before this commit everything compiles without issues, on it and after - I'm getting SIGTRAP.

**Comment by envenomator** [comment]
Ah ok. I don't support macOS as a target architecture.

**Comment by nihirash** [comment]
I've found with LLDB where buffer overrun happened. 

Increasing this value fixes buffer overrun(SIGTRAP happening on `strcpy` call and issue will happens even on linux/mos anyway): 
https://github.com/envenomator/agon-ez80asm/blob/fbc45c511b15df110fb5e0a37dba88792c48c2e6/src/config.h#L33
