### ISSUE TITLE
Buffer overrun on strcpy in parse_operand

### ISSUE THREAD

**Issue by nihirash** [envenomator/agon-ez80asm#84]
Issue https://github.com/envenomator/agon-ez80asm/issues/83 wasn't platform specific but was common for all platforms - buffer overrun on strcpy.

In my case buffer overrun happens here: https://github.com/envenomator/agon-ez80asm/blob/fbc45c511b15df110fb5e0a37dba88792c48c2e6/src/assemble.c#L357

As operand in context was calculating between two labels `term_free_cmd_end - term_free_cmd`(33 bytes, when maximum size was 32) - so this situation is possible for another cases too. 

Simplest way move away issue - making this constant larger: https://github.com/envenomator/agon-ez80asm/blob/fbc45c511b15df110fb5e0a37dba88792c48c2e6/src/config.h#L33 

Best way - check string size before copying it to resulting buffer(and increase buffer size too).

**Comment by envenomator** [comment]
This is something I can work with. Too many people are dumping their git repo URL to me, stating 'this doesn't work'. Combine this with a platform I'm not supporting (which I get lots of questions about, even when I'm not releasing binaries for these), not a good combination.

I can reproduce this issue. It happens during the operand stage, when the operand itself has a maximum of LINEMAX characters at read, while the buffer is defined as MAXNAMELENGTH. I'll fix this in the next release.

**Comment by nihirash** [comment]
Sorry, I'll try be a bit more correct next time.

**Comment by envenomator** [comment]
Fixed as part of release v1.8
