### ISSUE TITLE
.org isn't behaving as expected

### ISSUE THREAD

**Issue by Philbywhizz** [envenomator/agon-ez80asm#86]
It appears that ez80asm isn't honoring .org changes in the middle of the file.

Take for example the simple hello.asm file in the below gist. If I want to have the 'string' further down memory, I put a .org $40100 entry in. It shows up in the listing that the string is located at $40100. The ez80asm output also shows that 275 bytes written, however when you hexdump the file the string is still at $40064 and the bin file length is still at 119 bytes. 

Sijnstra from Discord pointed out that adding an align directive works, but that seems a bit clunky

I have the 3 outputs here for reference and ease of replayability:
https://gist.github.com/Philbywhizz/125d5d5dfa3ba4f9c49d43da53631c0b

**Comment by envenomator** [comment]
For ez80asm, the .org directive was never intended to be used multiple times; just once in the beginning of the first source file. The docs do mention 'no padding', but could have been clearer on this.

While I can't immediately see a use case for this, I'll implement this as an enhancement in the next release and make sure that bytes are padded using the currently defined fillbyte. I'll also need to make sure to produce an error when the current program counter is advancing beyond any manually stated .org directives.

**Comment by Philbywhizz** [comment]
Hi @envenomator, there isn't a specific use case here - it was just myself messing around with the assembler itself trying to understand and learn how it all works.

**Comment by sijnstra** [comment]
Thank you @envenomator for working on this. I had a look through my code and realised why I use this feature. It becomes an very manual and old way of effectively having code segments. I use it a bit on my source that's compiled with zmac.

**Comment by envenomator** [comment]
Released in v1.9
