### ISSUE TITLE
assemble error with macro - inline maths??

### ISSUE THREAD

**Issue by richardturnnidge** [envenomator/agon-ez80asm#87]
I am revisiting my Lunar Lander game, try to improve some of the motion.
Before making any changes to my previous master sources, I tested assembling on the latest ez80asm, but it failed.

In version 1.4, this assembles fine. But, with 1.9, it gives an error.
I haven't tested with any intermediate releases as I hadn't used any on my Mac.
As we have seen before, it may not be anything to do with this line at all!!

I am building a string of data to send to VDP with some macros.

eg.
    MAKEBUFFEREDBITMAP 20, 320, 120, "resources/lunar_title.pbm", titleColour

(titleColour is an EQU)

Where the macro starts with:

	macro MAKEBUFFEREDBITMAP bitmap_id, width, height, data, colourCode

	; create buffer

	.db 	23,0,$A0 							; write block
	.dw 	64000 + bitmap_id 							
	.db 	3	 								; 'create' command
	.dw 	width *  height / 8 				; data size = length 320 x 64 / 8 bits as b/w

It gives assemble error of:

Pass 1...
Pass 2...
[31mMacro [MAKEBUFFEREDBITMAP] in "macros.inc" line 307 - Unknown label, invalid number[33m 'bitmap_id'
[39m[33m	.dw 	64000 + bitmap_id
[39m[31mInvoked from "lander_29.asm" line 1732 as
[33m 	MAKEBUFFEREDBITMAP 20, 320, 120, "resources/lunar_title.pbm", titleColour

If I step through each line in the macro and remove any of the maths (+ *, /, etc) it no longer reports an error for that line.

So, is there an issue doing basic maths within a macro now??

**Comment by envenomator** [comment]
Looks like a bug, probably due to changed token handling after 1.4.

**Comment by envenomator** [comment]
Please try to build from the latest master branch to see if this indeed fixes the issue

**Comment by envenomator** [comment]
Latest commit adds the possibility to have argument names that partly overlap, like 'arg', 'arg1' and 'argument', while still expanding them correctly in the macro.

**Comment by richardturnnidge** [comment]
Very quick build before bed, but I think that has done it!!! thank you. I will test further tomorrow.
I put an extra version comment in so I knew for sure which version I was running!!
My Sublime build script output as follows:


Build script for AgonLight2
File: lander_29.asm 
 -----------------------------------------
ez80asm version 1.9, (C)2024 - Jeroen Venema
Mac build R. Turnnidge macro fix?
Exporting symbols
Assembling lander_29.asm
Listing to lander_29.lst
Pass 1...
Pass 2...
Done in 0.03 seconds

Assembly statistics
 ======================
Label memory  : 12286
Labels        : 284

Macro memory  : 8817
Macros        : 39

Input buffers : 193207
 ---------------------
Total memory  : 214310

Sources parsed: 7
Binfiles read : 44

Output size   : 128608
Created BIN v1.9 file: lander_29.bin 
 -----------------------------------------
Making HEX file: lander_29.hex 
Making emulator local copy: lander_29.bin
Hex file made
 -----------------------------------------

**Comment by envenomator** [comment]
Fixed in release v1.10
