### ISSUE TITLE
Strange behavior of character literals

### ISSUE THREAD

**Issue by nihirash** [envenomator/agon-ez80asm#9]
For example, I can make:
```
 CP 'K'
 CP 'E'
CP 'K'
```

But I can't do: 
```
  CP '+'
  CP ','
```

In last case I'm getting "Invalid ascii format" message.

**Comment by envenomator** [comment]
These were actually two separate issues. Both are fixed in commit e812186

**Comment by envenomator** [comment]
I'll provide a new release this weekend
