### ISSUE TITLE
order of EQU calculations now critical

### ISSUE THREAD

**Issue by richardturnnidge** [envenomator/agon-ez80asm#91]
Again, trying to build an older bit of mole bashing code...

This Fails:
imgData:					
   	incbin "resources/title_target.pbm" 		
endImgData:

DEFBUFFERSIZE:	equ 	DEFFILESIZE * 32	; file size x 8 bits x 4 colours RGBA  ; 61440	; 320 x 48 x 4 bytes
DEFFILESIZE:	equ	endImgData - imgData 	; DEFBUFFERSIZE/32

But if I work out the maths, it works:
DEFBUFFERSIZE:	equ 	61440 ;DEFFILESIZE * 32
DEFFILESIZE:	equ	1920 ;endImgData - imgData

So maybe the EQU is no longer working out any maths???

Pass 1...
[31mFile "mole_23.asm" line 1617 - Invalid number format[33m 'DEFFILESIZE'
[39m[33mDEFBUFFERSIZE:	equ 	DEFFILESIZE * 32	; file size x 8 bits x 4 colours RGBA  ; 61440	; 320 x 48 x 4 bytes

**Comment by richardturnnidge** [comment]
### **UPDATE**

Just done a new build of v10 to make sure I am on the latest.

On a new test, I found out the order is now important. This never used to be the case. But at least I know what the issue is and how to resolve.

If the second operation is completed first, the equ is defined properly and the first can be calculated.
The first calculation relied on the value being created by the second, which had not happened yet.

So, the following order works:

DEFFILESIZE: equ endImgData - imgData ; DEFBUFFERSIZE/32
DEFBUFFERSIZE: equ DEFFILESIZE * 32 ; file size x 8 bits x 4 colours RGBA ; 61440 ; 320 x 48 x 4 bytes

**Comment by envenomator** [comment]
True, this changed a while back so fix an issue. To avoid adding in a third assembly pass, I documented the order in which .equ's can be used with other .equ's. This is in the 'EQU labels' section in the docs.

**Comment by richardturnnidge** [comment]
Thanks, I didn't look at the docs, as it had worked previously.
I see that is implied in the last paragraph, although I would not personally have read that to mean the issue I encountered!

However, now I understand, all sorted :-)

**Comment by envenomator** [comment]
Released as v1.11
